### ISSUE TITLE
Add note to default email templates that states replies will be public when using RVE

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#123]
When RVE (Replies via Email) is enabled, it's important that the default email template(s) include(s) a note that says:

> **Please Note:** Your reply will be posted publicly and immediately.

That note should be included immediately after any instructions about how the reader can simply reply to the email to reply to the comment.

This is important because email is inherently private, so it would be easy for someone to hit reply on a notification and just assume that they're sending a private reply to the site owner! (I've had many readers do exactly that on my personal blog.)

**Comment by jaswsinc** [comment]
:+1:

**Comment by jaswsinc** [comment]
# Next Actions

## Prerequisites

Work on this issue requires a basic knowledge of PHP. It could be a good learning experience. If you need help editing the PHP template files referenced below, please feel free to ask for help on Slack in the #comment-mail channel.

### `~/projects/websharks` Directory

_Please create a folder in your HOME directory named: `websharks`; e.g., `/Users/[YOURNAME]/websharks`. This folder will be referenced in the instructions below, and it can be used as a place for all of your WebSharks-related projects to live._

### Git Command-Line Tool

If you're running Windows, see: https://msysgit.github.io/
If you're running Mac, install via Homebrew: `brew install git`
If you're running on Linux: `sudo apt-get install git`

---

## Clone Comment Mail and Comment Mail Pro Repos

```bash
$ git clone --recursive https://github.com/websharks/comment-mail-pro ~/projects/websharks/comment-mail-pro
$ git clone --recursive https://github.com/websharks/comment-mail ~/projects/websharks/comment-mail
```

You should now have two repos locally.

- `~/projects/websharks/comment-mail-pro`
- `~/projects/websharks/comment-mail`

---

## Start Two New Feature Branches

Feature branches are going to be created so that your changes take place in a separate branch. After you complete work, you'll submit pull requests at GitHub requesting that changes in your feature branches be merged into the official copy.

### Pro Version

```bash
$ cd ~/projects/websharks/comment-mail-pro # Move to the comment-mail-pro repo.
$ git checkout 000000-dev # Always start from the dev branch.
$ git pull # Make sure you have the latest copy of the dev branch.
$ git checkout -b feature/123 # Create and checkout a new feature branch.
```

### Lite Version (Almost the Same)

```bash
$ cd ~/projects/websharks/comment-mail # Move to the comment-mail repo.
$ git checkout 000000-dev # Always start from the dev branch.
$ git pull # Make sure you have the latest copy of the dev branch.
$ git checkout -b feature/123 # Create and checkout a new feature branch.
```

---

## Make Changes

Using an editor of your choosing, please follow this general outline:

### Pro Version

- Add the instructions Raam mentioned after this line: https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/includes/templates/type-a/email/comment-notification/message.php#L160

- Add the same instructions to the simple template variation also: https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/includes/templates/type-s/email/comment-notification/message.php#L165

### Lite Version

- Add the instructions Raam mentioned after this line: https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/templates/type-s/email/comment-notification/message.php#L165

_The lite version comes with the simple templates only, so only one file to edit in the lite version._

---

## Commit Changes

### Pro Version

```bash
$ cd ~/projects/websharks/comment-mail-pro
$ git add --all && git commit -m 'Adding RVE instructions. See: websharks/comment-mail#123'
$ git push -u origin feature/123
```

### Lite Version (Almost the Same)

```bash
$ cd ~/projects/websharks/comment-mail
$ git add --all && git commit -m 'Adding RVE instructions. See: websharks/comment-mail#123'
$ git push -u origin feature/123
```

---

## Submit Pull Requests

Come to GitHub.com and submit two Pull Requests.

### Pro Version

- See this page which is a [list of all pro branches](https://github.com/websharks/comment-mail-pro/branches).
- Find your feature branch in the list; i.e., `feature/123`
- Click "New Pull Request"
- Enter a title; e.g., "RVE Instructions; see: websharks/comment-mail123"
- Enter a body; e.g., "Closes websharks/comment-mail123"
- Click submit.

### Lite Version

- See this page which is a [list of all lite branches](https://github.com/websharks/comment-mail/branches).
- Find your feature branch in the list; i.e., `feature/123`
- Click "New Pull Request"
- Enter a title; e.g., "RVE Instructions; see: websharks/comment-mail123"
- Enter a body; e.g., "Closes websharks/comment-mail123"
- Click submit.

**Comment by jaswsinc** [comment]
Assigning this to @Reedyseth in hopes that he could help us with this one.

**Comment by Reedyseth** [comment]
Hey @jaswsinc I will take a look at this and let you know,

**Comment by Reedyseth** [comment]
Done @raamdev @jaswsinc 

![image](https://cloud.githubusercontent.com/assets/1228711/8859792/d3c90e8c-313c-11e5-8a47-7474bfb30335.png)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Added a note to the default email templates when RVE (Replies via Email) is enabled, warning email readers that "Your reply will be posted publicly and immediately." Props @Reedyseth. See [Issue #123](https://github.com/websharks/comment-mail/issues/123).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Added a note to the default email templates when RVE (Replies via Email) is enabled, warning email readers that "Your reply will be posted publicly and immediately." Props @Reedyseth. See [Issue #123](https://github.com/websharks/comment-mail/issues/123).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#123).
