### ISSUE TITLE
StCR Import Bug: "All Replies" subscriptions treated as "Replies Only To Self"

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#162]
## Steps to reproduce this bug

1. Install, activate, and enable StCR
1. Leave a comment on a post and select "All" to receive notifications for all new comments on the post
1. Install, activate, and enable Comment Mail Lite (confirmed with v150709)
1. Run the StCR → Comment Mail import process to import the StCR subscription
1. Disable StCR
1. Leave a new comment on the post that contained the subscription you imported

## Expected behavior

Comment Mail should send a notification to the imported subscription.

## Observed behavior

No email is sent.

---

### What appears to be happening

If you edit the imported StCR subscription inside **Comment Mail → Subscriptions**, you'll notice how it appears to have been imported as a "replies only" subscription (because a Comment ID is selected). However, what's really strange is that the comment selected _is itself_.

In the screenshot below you can see that the comment selected in "Comment ID" is the same as the subscription being edited!

![2015-11-23_16-31-33](https://cloud.githubusercontent.com/assets/53005/11350586/4144ad80-9200-11e5-9f0f-7cebb012a6d9.png)

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **StCR Import Bug Fix:** This release corrects an StCR importation bug. The bug was causing an existing StCR subscription with a `Y` status (i.e., one for all comments/replies) to be imported into Comment Mail on a per-comment basis. Therefore, a symptom of this bug was to find that you had multiple subscriptions imported for users who wanted _all_ comments, instead of them just having one subscription imported which would automatically cover the entire post. Props @raamdev for reporting this. See also [this GitHub issue](https://github.com/websharks/comment-mail/issues/162) for technical details.

**Comment by jaswsinc** [comment]
> However, what's really strange is that the comment selected is itself.

_@raamdev I found no correlation between the comment ID and the subscription ID. I think that may have just been a coincidence. I noticed this happening too, but it was only because I had a new install to test with and the likelihood of that occurring was higher._

**Comment by jaswsinc** [comment]
## Summary of StCR Import Behavior

- If the existing subscription has a `Y` (all comments) status, one new subscription is imported for that subscriber; i.e., they are subscribed to all comment/replies on a given post.

- If an existing subscriber has no `Y` status, or has any `R` (replies only) status, instead of subscribing the user to all comments/replies, we import subscriptions on a per-comment basis, and they are only subscribed to comments where they were the original author.

**Comment by Reedyseth** [comment]
Is this related to #166 ?

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#162).
