### ISSUE TITLE
Edit Subscription form (front-end) lets you clear the value of required fields

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#195]
When editing a subscription on the front-end, the **Status** and **Deliver** fields have a little "X" in them that allows you to clear the value of that field. This doesn't make sense, since those fields are required and there is no reason to empty them.

![2015-12-26_18-14-05](https://cloud.githubusercontent.com/assets/53005/12008254/f95007b0-abfc-11e5-87df-cbf051766eac.png)

![2015-12-26_18-15-56](https://cloud.githubusercontent.com/assets/53005/12008256/190d4d2e-abfd-11e5-9ae4-b70d5f30ee41.png)

_Note that this is purely a UI issue--if you clear the fields and try to update the subscription, you are properly informed that you must select a value for those fields._

**Comment by jaswsinc** [comment]
:+1:

**Comment by kristineds** [comment]
@raamdev @jaswsinc If you could create an outline for this, I'll be happy to work on it. :)

**Comment by jaswsinc** [comment]
## Next Actions

- In [these lines](https://github.com/websharks/comment-mail/blob/4b3706cc5b07cbe753c9c59151b7ab3c436dc324/comment-mail/includes/templates/type-s/site/sub-actions/manage-sub-form.php#L333-L334) replace `chosenOps` w/ the following:

  ```js
  $.extend({}, chosenOps, {allow_single_deselect: false})
  ```

- Repeat in the `type-a` templates folder also.

- _Repeat both steps in the pro version._

**Comment by jaswsinc** [comment]
Referencing: http://alxlit.name/bootstrap-chosen/
~ The Bootstrap JS plugin that powers those select menus.

**Comment by kristineds** [comment]
@jaswsinc Is the code supposed to look like this?

```php
$('.manage-sub-form form tr.manage-sub-form-status select').chosen($.extend({}, chosenOps, {allow_single_deselect: false}));
$('.manage-sub-form form tr.manage-sub-form-deliver select').chosen($.extend({}, chosenOps, {allow_single_deselect: false}));
```

I tried testing it on my site but nothing was changed. :( What am I missing?
Also, I'm not seeing any `type-a` template folder on the `comment-mail` [repo](https://github.com/websharks/comment-mail/tree/4b3706cc5b07cbe753c9c59151b7ab3c436dc324/comment-mail/includes/templates)

**Comment by raamdev** [comment]
> Also, I'm not seeing any type-a template folder on the comment-mail repo

The `type-a` directory is for Advanced Templates, which are only available with Comment Mail Pro.

**Comment by jaswsinc** [comment]
> Is the code supposed to look like this?

Looks great, yes.

> I tried testing it on my site but nothing was changed. :(

Whenever you tested did you have the Simple Templates enabled in Comment Mail? Or the Advanced Templates? If you haven't updated the Advanced Templates yet, you might not see the changes.

Also, keep in mind that I haven't tested this change myself yet. I'm outlining, and it should work; well, because I want it to (code is forced to do as I wish, LOL). However, there are times when my magic powers are not working right. So if that's the case (i.e., just not working), give me another shout :-)

**Comment by kristineds** [comment]
> Whenever you tested did you have the Simple Templates enabled in Comment Mail? Or the Advanced Templates? If you haven't updated the Advanced Templates yet, you might not see the changes.

I tested this just now for Comment Mail Pro:
-  File uploaded for both `type-s` & `type-a` folder
-  Tried enabling Simple Templates, and checked "Edit subscriptions" to see if anything was changed, got nothing. 
- Did the same for Advanced Templates, still nothing
- Turned Safeguard Data off, and run the test again, still nothing. 

_Not sure what I'm missing_

**Comment by jaswsinc** [comment]
Thanks Kristine! :-)

Hmm, it looks like this option may not do what I thought. I suppose I should have thought about the name of this option some more. Now that I'm looking at it again, I think what this controls is the behavior associated with only **single** option; i.e., if there were only _one_ option in the dropdown, it would allow you to enable/disable the close icon for that specific scenario. If that's the case, then that explains why it is not working for you like I thought it would.

Still, it's good that you made that change, because we don't want it enabled for that case either.

---

Now, to get this resolved, let's just use some CSS.

- In [this file](https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/client-s/css/bootstrap-chosen.css) add the following, compress it into the `.min.css` variation and experiment.

```
.chosen-container-single-nosearch.search-choice-close {
  display: none !important;
}
```

**Comment by kristineds** [comment]
> In this file add the following, compress it into the .min.css variation and experiment.

I did this but it's not hiding the `x` clearing option on those fields. 

However, if I try to disable it for `.chosen-container-single .chosen-single abbr` on th `chosen.min.css` file, it works.

**Comment by jaswsinc** [comment]
Cool! :-) Nice work. If that's what works then let's go with it. If you can update the PR here and make this change in the lite version also, then we can merge this enhancement in. https://github.com/websharks/comment-mail-pro/pull/45

**Comment by kristineds** [comment]
> If that's what works then let's go with it.

Problem is I can't find the `chosen.min.css` file. :(  Where is it located? I tried adding it on `bootstrap-chosen.min.css` file but it doesn't work either. 

![screen shot 2016-01-19 at 5 08 06 am](https://cloud.githubusercontent.com/assets/7514953/12402878/e6dc4fb4-be6a-11e5-9e78-f96b26f8d5d1.png)

**Comment by kristineds** [comment]
@jaswsinc Can you help me with this please? :) https://github.com/websharks/comment-mail/issues/195#issuecomment-172655004 cc @raamdev

**Comment by jaswsinc** [comment]
> Problem is I can't find the chosen.min.css file. :( Where is it located?

That CSS file is loaded from a CDN and so you cannot edit it directly.
See: https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/templates/type-a/site/header-styles.php#L24

> I tried adding it on bootstrap-chosen.min.css file but it doesn't work either.

It should work in that file, because that file is loaded _after_ the base copy from the CDN.
See: https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/templates/type-a/site/header-styles.php#L25

You might need to use `!important` to override something from the base though. Or just work at making the rule have a higher precedence. See: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Improved the front-end Edit Subscription form and removed the "x" in on the Status and Deliver fields that allowed clearing those fields, which did not make sense since both of those fields are required. Props @kristineds. See [Issue #195](https://github.com/websharks/comment-mail/issues/195).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved the front-end Edit Subscription form and removed the "x" in on the Status and Deliver fields that allowed clearing those fields, which did not make sense since both of those fields are required. Props @kristineds. See [Issue #195](https://github.com/websharks/comment-mail/issues/195).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#195).
