### ISSUE TITLE
Avoid display of "Back to subscriptions" button when no subscription available to the user.

### ISSUE THREAD

**Issue by Reedyseth** [websharks/comment-mail#229]
I noticed that on the `Add Subscription` page there is a button to return to my subscriptions, so I clicked on it an got an error retrieving my subscription. An enhacement could be to not display that button if there are not subscriptions associated

![image](https://cloud.githubusercontent.com/assets/1228711/12999234/62cfcd06-d10a-11e5-8307-16505df6bdda.png)

This is display when I click on the button

![image](https://cloud.githubusercontent.com/assets/1228711/12999348/561f2c86-d10b-11e5-8f98-e7df4745ae33.png)

**Comment by kristineds** [comment]
I was able to replicate this error after subscribing without commenting on a post as a non logged-in user. Also, after creating my subscription, I encountered that error again when I clicked on _Back to My Subscriptions_. If a confirmation from the subscriber needs to be made before one can view their subscriptions, shouldn't there be a note to say that instead of the error message? 

![screen shot 2016-02-12 at 2 12 01 pm](https://cloud.githubusercontent.com/assets/7514953/13000253/2bbeffe2-d193-11e5-9d1d-584da1592dad.png)

**Comment by renzms** [comment]
@raamdev @Reedyseth  @kristineds 

![screen shot 2016-02-12 at 5 11 47 pm](https://cloud.githubusercontent.com/assets/13220018/13002726/c0229bc2-d1ab-11e5-8688-c39931ce9dc6.png)

Working fine on my end.

- subscribed to a new post without commenting
- When asked for the delivery option I chose `instantly`
- On the next page I clicked the **Back to My Subscriptions** link
- Subscriptions displaying successfully

I did however experience this before in an older version of Comment-Mail, https://github.com/websharks/comment-mail/issues/134#issuecomment-167939644

The issue disappeared after disabling all plugins except Comment-Mail Pro. When I re-enabled all plugins again, everything was still working fine.

**Comment by raamdev** [comment]
@renzms writes...
> Working fine on my end.

Are you logged in? That screenshot looks like you might be logged in, or you might already have a bunch of subscription associated with the `renz@websharks-inc.com` email address, so the page that lists the subscription will work as expected. 

I believe @kristineds and @Reedyseth are referring specifically to **non-logged-in users**, as Kristine mentioned in her last comment.

---

I was able to confirm the behavior that Israel and Kristine have observed:

### Scenario 1 (not logged in)

1. Visit a post as a user who IS NOT logged in
1. Click the "Subscribe without Commenting" link on a post
1. When you get to the "Add New Subscription" page, try clicking the Back icon or the "My Comment Subscriptions" link at the bottom 

     **OR** 

     Click "Create Subscription" at the bottom and when you see the success message, try clicking the "Back to My Subscriptions" link

### Scenario 2 (logged in, no subscriptions)

1. Visit a post as a user who IS logged in but has NO subscriptions
1. Click the "Subscribe without Commenting" link on a post
1. When you get to the "Add New Subscription" page, try clicking the Back icon or the "My Comment Subscriptions" link at the bottom 

     **OR** 

     Click "Create Subscription" at the bottom and when you see the success message, try clicking the "Back to My Subscriptions" link

![2016-02-12_09-40-21](https://cloud.githubusercontent.com/assets/53005/13009898/ed86e314-d16c-11e5-82f8-d5d1dfb4dc80.png)
![2016-02-12_09-40-35](https://cloud.githubusercontent.com/assets/53005/13009899/ee39ad50-d16c-11e5-97b3-09321a5307d1.png)
![2016-02-12_09-41-21](https://cloud.githubusercontent.com/assets/53005/13010399/adef6048-d16f-11e5-9d8c-63bea15de4e2.png)

In all cases, that link leads to a page with an error:

![2016-02-12_09-42-53](https://cloud.githubusercontent.com/assets/53005/13009916/fffcebba-d16c-11e5-8b33-d894b8d0c9f7.png)

This error makes sense, because **there are no subscriptions to list for this user because they are not yet known to Comment Mail** (i.e., they don't have a Subscription Key yet). Once they confirm their first subscription, a Subscription Key is created for them and whenever they visit those pages after confirming their subscription, the presence of the key (for non-logged-in users) makes all of the pages work (for logged-in users, they just need to have a confirmed subscription; the key does not need to be present in the URL).

---


## How this needs to be fixed

So, what we need to do is detect various scenarios where those links would lead to that error page and hide them so that users cannot easily reach that error page and get confused.

From what I've tested, these are the two common scenarios where those links should be hidden:

- User is **not** logged in and no Subscription Key is present
- User **is** logged in but does not have any subscriptions

**Comment by renzms** [comment]
> Are you logged in?

Yes, I tried it without being logged in and now I see the error now too.

> From what I've tested, these are the two common scenarios where those links should be hidden:
> 
> User is not logged in and no Subscription Key is present
> User is logged in but does not have any subscriptions

Agree, I tried both scenarios also to duplicate and used a 3rd scenario.

 - User is not logged in, **subscribes** for the first time and then **subscribes again** on the success page selecting a different post from the dropdown without first confirming their **first subscription**.

**Comment by raamdev** [comment]
@renzms writes...
> User is not logged in, subscribes for the first time and then subscribes again on the success page selecting a different post from the dropdown without first confirming their first subscription.

Can you provide screenshots please? I'm not following...

**Comment by Reedyseth** [comment]
> So, what we need to do is detect various scenarios where those links would lead to that error page and hide them so that users cannot easily reach that error page and get confused.

@raamdev I can work on this issue if it is ok with you ?

**Comment by raamdev** [comment]
@Reedyseth Sure. :-)

**Comment by jaswsinc** [comment]
@Reedyseth Here are some lines that should help you out.

```php
$current_email     = $this->plugin->utils_sub->currentEmail();
$has_subscriptions = $current_email ? (bool)$this->plugin->utils_sub->queryTotal(null, ['sub_email' => $current_email, 'status' => 'subscribed', 'sub_email_or_user_ids' => true]) : false;
```

So a conditional might then look something like this...

```php
if ($is_edit || ($current_email && $has_subscriptions)) {
    // Display the link.
}
```

See also: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/UtilsSub.php#L566

**Comment by Reedyseth** [comment]
@raamdev 
This pull request closes this issue https://github.com/websharks/comment-mail-pro/pull/71

Thanks for the help !

**Comment by kristineds** [comment]
@raamdev I tried changing this [line of code](https://github.com/websharks/comment-mail-pro/pull/71/commits/09170beae815c42810a058fb8227cee45c3908f8#diff-38620980f8520d9d9cd24c9937558980R37) to this:

```php
$sub_summary_return_url = $has_subscriptions && $plugin->utils_url->subManageSummaryUrl($sub_key, null, true);
```

But I'm getting this error message ([found here](https://github.com/websharks/comment-mail-pro/blob/6d2629d4c2815bc6a6c3448992896c2a82517121/src/includes/classes/UtilsPhp.php#L91)):

>Parse error: syntax error, unexpected 'elseif' (T_ELSEIF), expecting end of file in /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail-pro/src/includes/classes/UtilsPhp.php(87) : eval()'d code on line 91

Any idea how to fix it? :) cc @jaswsinc

**Comment by raamdev** [comment]
@kristineds It's not clear to me which line you're trying to change. The link you provided doesn't lead to a specific line, but rather to the entire diff, so I have no idea which specific line you're referring to. :-)

**Comment by kristineds** [comment]
@raamdev Sorry about that. 😞  I'm trying to change this line: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/templates/type-s/site/footer-tag.php#L34

Or should I be looking at another file to fix this issue?

**Comment by raamdev** [comment]
This line doesn't look right to me because it's basically giving `$sub_summary_return_url` a boolean `true`/`false` value, which is not what you want.

```php
$sub_summary_return_url = $has_subscriptions && $plugin->utils_url->subManageSummaryUrl($sub_key, null, true);
```

Can you explain to me what you're trying to do on that line?

**Comment by kristineds** [comment]
@raamdev Since the error message that I'm getting (when clicking on the Back button) is because of a missing `$sub_key`, https://github.com/websharks/comment-mail-pro/blob/6d2629d4c2815bc6a6c3448992896c2a82517121/src/includes/templates/type-a/site/sub-actions/manage-summary.php#L104

```
Missing subscription key; unable to display summary
```

I'm _trying_ to fix the issue you pointed out here. https://github.com/websharks/comment-mail-pro/pull/71#discussion_r67532363

If I'm looking at it the wrong way, please point me to the right direction. :)

**Comment by raamdev** [comment]
> I'm trying to fix the issue you pointed out here. websharks/comment-mail-pro#71 (comment)

Have you confirmed there's even an issue there? :-)

**Comment by raamdev** [comment]
Next Release Changelog:

- **Bug Fix**: Fixed a bug where the "My Comment Subscriptions" link would appear on the Add New Subscription page (when Subscribing without Commenting) and would lead to a page that displayed an error message stating that there were no subscriptions to list. That link is now hidden when there are no subscriptions to list. Props @Reedyseth @kristineds. See [Issue #229](https://github.com/websharks/comment-mail/issues/229).

**Comment by raamdev** [comment]
**Comment Mail v160818** has been released and includes changes from this GitHub Issue. See the [v160818 announcement](http://comment-mail.com/comment-mail-v160818-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#229).
