### ISSUE TITLE
Improve information displayed on the Post Meta Box

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#231]
It would be nice to improve the information displayed on the Post Meta Box to include the subscription time. Also, have the subscriber’s name displayed instead of their email address.

**Before:**

![screen shot 2016-02-12 at 6 18 51 pm](https://cloud.githubusercontent.com/assets/7514953/13004294/a29c0aca-d1b5-11e5-828f-af6b9393b6c7.png)

**After:**

![screen shot 2016-02-12 at 2 03 31 pm](https://cloud.githubusercontent.com/assets/7514953/13004305/ac7b9b3c-d1b5-11e5-8386-dbcf60b7ebfa.png)

**Comment by raamdev** [comment]
:+1:

**Comment by raamdev** [comment]
Some more thoughts on this:

- Linking the email address to the subscription itself is _very_ counterintuitive. When I see the link around the email address, I immediately assume that clicking that link is the same as clicking any other email address: i.e., it's going to try and open my default email client to send that person an email. So, whatever we do here, we need to NOT use the email address as a link to the subscription; that just doesn't make sense.
- Now that this Post Meta box is of the wider variation (instead of the sidebar variation), we can make use of that extra space to show a bit more information. I like that idea. It makes that box look a bit more like a log of recent subscriptions.
- The "6 days ago", "20 hours ago" feature that Kristine suggested looks nice and I would follow the same format that we use in the Subscriptions list, e.g., "Feb 11, 2016 3:20pm (_20 hours ago_)".
- The link at the very top that says the total number of subscriptions has a few issues, namely that it doesn't look like a button or a link. I suggest moving that to the bottom of the list (which makes sense... you view the list of most recent subscriptions, then if you want to view all of them you click the button to view all at the bottom).

Here's how I suggest we improve this Post Meta Box:

![2016-02-12_10-52-35](https://cloud.githubusercontent.com/assets/53005/13011904/fbeb3e28-d176-11e5-8164-1f99223b9883.png)

**Comment by jaswsinc** [comment]
This looks great!

![2016-02-12_10-52-35](https://cloud.githubusercontent.com/assets/53005/13011904/fbeb3e28-d176-11e5-8164-1f99223b9883.png)

**Comment by kristineds** [comment]
Nice! I love this. :+1: 

![2016-02-12_10-52-35](https://cloud.githubusercontent.com/assets/53005/13011904/fbeb3e28-d176-11e5-8164-1f99223b9883.png)

**Comment by raamdev** [comment]
Next Release Changelog:

- **Enhancement**: Improved the Subscriptions meta box that appears on the Post Edit screen. For each subscription, the meta box now lists the full name and email address, the date the subscription was created, and a view link that allows you to view/edit the subscription. Props @kristineds. See [Issue #231](https://github.com/websharks/comment-mail/issues/231).

**Comment by jaswsinc** [comment]
Woohoo! :-)

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#231).
