### ISSUE TITLE
Feature Request: Option to disable comment clip in email notifications

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail#281]
It would be nice to have the option to disable comment clipping in email notifications to show the full comment, i.e, using HTML in comments without it being converted to plain text and full content length.
## Current Workaround

Currently, the only way to prevent a comment from being clipped/stripped of HTML in the comment notification email is to modify the Advanced Templates and remove the function that is clipping the comment. 
## Problem

This fix is only applicable for Pro users, but currently not an option for Lite users since Advanced Templates are only available in the Pro version.
## Solution

Add an option for both Lite and Pro users to turn off automatic clipping in the menus.

**Comment by jaswsinc** [comment]
Another +1 for this here in a private/internal ticket:
https://websharks.zendesk.com/agent/tickets/13056

**Comment by jaswsinc** [comment]
## Quick Outline

There are two functions in Comment Mail that deal with clipping of the comment content body specifically, and therefore instead of going through each template file it might be easier just to filter these methods so that you can change this behavior easily.

- See: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/UtilsMarkup.php#L790

- See: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/UtilsMarkup.php#L816

So what is needed is a new configurable option, and then have these two methods look for that option and either _do_ the clipping, or skip the clipping altogether.

**Comment by jaswsinc** [comment]
It seems this is already possible. See attached screenshot.

![2016-12-02_01-16-20](https://cloud.githubusercontent.com/assets/1563559/20830487/23b7a8a4-b82d-11e6-9a60-b1be801bb75b.png)

**Comment by renzms** [comment]
@jaswsinc 

> It seems this is already possible. See attached screenshot.


This feature needs to be added in the Lite version as well. :)

>**Problem**
>**This fix is only applicable for Pro users, but currently not an option for Lite users since Advanced Templates are only available in the Pro version.**

![screen shot 2016-12-02 at 11 04 37 pm](https://cloud.githubusercontent.com/assets/13220018/20838640/697e9c6e-b8e4-11e6-8a4b-c776210bafcc.png)

**Comment by raamdev** [comment]
@jaswsinc writes...
> It seems this is already possible. See attached screenshot.

So how do we disable clipping in the email templates?

Oh... now I get it. You have to set the minimum lengths to very large numbers and the resulting effect is the same as not clipping...

**However**, the problem with this is that the content still runs through the clipping function, which destroys things like line breaks, so if you want multi-paragraph comments to show up as multi-paragraph comments in your email templates, setting the minimum clip lengths to a large number does not do it... we need to edit the templates and strip out that clipping method.

So, an option is still necessary here. We need something that allows a site owner to disable clipping, which should have the effect of stripping out the clip function from the email templates (e.g., have the clipping function check if clipping is disabled and simply return without doing anything).

**Comment by jaswsinc** [comment]
I see. Great points all around. I'll add this in just a moment.

**Comment by jaswsinc** [comment]
![2016-12-03_00-27-04](https://cloud.githubusercontent.com/assets/1563559/20858299/7ac18472-b8ef-11e6-8533-5e991ab93eeb.png)
![2016-12-03_00-26-50](https://cloud.githubusercontent.com/assets/1563559/20858300/7aead3fe-b8ef-11e6-88d1-bc2fc1717e4d.png)

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **New Feature:** In Comment Mail Pro it is now possible to enable/disable comment content clipping entirely; e.g., if you prefer that email notifications include the full original comment content in raw HTML instead of being clipped and displayed in the email as plain text. See: **WP Dashboard → Comment Mail → Config. Options → Email Notification Clips**. See also: [Issue #281](https://github.com/websharks/comment-mail/issues/281).

**Comment by jaswsinc** [comment]
The following Simple template replacement codes are now deprecated:

- `[comment_clip]` is deprecated; use `[comment_content]`
- `[comment_parent_clip]` is deprecated; use `[comment_parent_content]`

The old replacement codes will continue to work, but since the behavior of these replacement codes is now dependent upon clipping being enabled or disabled by CM options, the name of these has changed along with the description they have in the UI.

**Comment by jaswsinc** [comment]
@renzms If you can help me test this I'd appreciate it. I implemented the new logic and config. option, but I have not yet tested receiving email notifications since this change was made.

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed Working


Tested using Comment Mail v161210 Pro/Lite RC and WP 4.7.

### Comments on front end

**With Clipping**
![screen shot 2016-12-13 at 5 24 33 pm](https://cloud.githubusercontent.com/assets/13220018/21134555/65814378-c159-11e6-8ff1-134e45694541.png)
**Without Clipping**

![screen shot 2016-12-13 at 5 26 30 pm](https://cloud.githubusercontent.com/assets/13220018/21134552/657e8c32-c159-11e6-84ad-c38a00856dcf.png)


### Backend Clip Settings

**With Clipping**
![screen shot 2016-12-13 at 5 31 51 pm](https://cloud.githubusercontent.com/assets/13220018/21134709/1614ea82-c15a-11e6-987f-3ff77b6d58fc.png)


**Without Clipping**
![screen shot 2016-12-13 at 5 31 44 pm](https://cloud.githubusercontent.com/assets/13220018/21134710/173ca210-c15a-11e6-8a45-5a0ca151a5f9.png)



### Email Notifications

**With Clipping**

![screen shot 2016-12-13 at 5 26 46 pm](https://cloud.githubusercontent.com/assets/13220018/21134553/657e925e-c159-11e6-8192-8dd9efdcff00.png)

**Without Clipping**

![screen shot 2016-12-13 at 5 26 57 pm](https://cloud.githubusercontent.com/assets/13220018/21134554/657ed7f0-c159-11e6-87f8-146e8ea12bbc.png)

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#281).
