### ISSUE TITLE
Subscribe without commenting shows unapproved comments

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#299]
I just saw something weird in my Subscriptions list and found this bug: Comments that were **not yet approved** are shown in the _subscribe without commenting_ page (Add New Subscription).

I had a user subscribed to a comment that I did not approved 😄

**Comment by raamdev** [comment]
@IvanRF Thanks for the report! We'll get this tested soon.

**Comment by renzms** [comment]
@raamdev 

Tested this under the following conditions:

- **WordPress 4.6.1** running **Twenty Sixteen theme** with **Comment Mail Pro Version 160818 / Comment Mail Version 160824** installed
- **Dashboard → Settings → Discussion →** *Check* `Comment must be manually approved`  
- Logged in/registered user and unregistered user comments

When commenting on a post as either a registered/unregistered user, the comment will appear to the user as an unapproved comment `awaiting moderation` after submission of the comment.

Hitting `reply` to the unapproved comment will allow the same user to `Subscribe without commenting` to the comment.

![screen shot 2016-09-30 at 1 19 05 pm](https://cloud.githubusercontent.com/assets/13220018/18981444/c97469d8-8710-11e6-9fd0-3f984afa3342.png)


They will then be taken to the `Add a new subscription` page, where they can view all comments, including the unapproved comments.

![screen shot 2016-09-30 at 1 19 48 pm](https://cloud.githubusercontent.com/assets/13220018/18981436/b947e6f2-8710-11e6-8abd-5a07d9694238.png)

**Comment by IvanRF** [comment]
Also, without hitting Reply if another user enters the page and just selects `Subscribe without commenting`, he will see the unapproved comment too.

**Comment by renzms** [comment]
> Also, without hitting Reply if another user enters the page and just selects Subscribe without commenting, he will see the unapproved comment too.

@raamdev 

I can confirm this as well, subscribing without commenting allows anyone to view the whole comments list *including* unapproved comments.

**Comment by raamdev** [comment]
@renzms Thanks for testing! That confirms this is a bug that needs to be fixed.

----

@jaswsinc Bug is as follows: Unapproved comments should **not** appear in the list of comments to subscribe to when subscribing without commenting.

**Comment by jaswsinc** [comment]
Copy that. Referencing [this block](https://github.com/websharks/comment-mail-pro/blob/160824/src/includes/classes/UtilsDb.php#L623). Estimate at 1 day.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Exclude unapproved comments from the dropdown menu on the 'Subscribe Without Commenting' form. See also: [issue #299](https://github.com/websharks/comment-mail/issues/299) for further details.

**Comment by raamdev** [comment]
@renzms Could you please test a `dev` build to confirm that this issue has been resolved?

**Comment by renzms** [comment]
@raamdev / @jaswsinc 

Hi Guys!

I can confirm that unapproved comments no longer appear in the Subscriptions list! 👍 

![screen shot 2016-11-04 at 8 11 45 pm](https://cloud.githubusercontent.com/assets/13220018/20005083/05e76304-a2cb-11e6-992b-7269ab829dad.png)


________





**However...**

I have observed a new minor issue with the Comment list field on the Subscriptions page.


## Expected Behavior:

- On posts that have an already approved Comment, the field appears with a dropdown menu.

![screen shot 2016-11-04 at 8 11 38 pm](https://cloud.githubusercontent.com/assets/13220018/20005098/1804a556-a2cb-11e6-89ca-6ee4e3e57e66.png)

## Observed Behavior:

- On posts that have no comments at all, the field appears to have arrows for entering numerical values.

![screen shot 2016-11-04 at 8 11 27 pm](https://cloud.githubusercontent.com/assets/13220018/20005109/32c5dd10-a2cb-11e6-98b3-a32746fdd2f2.png)

![screen shot 2016-11-04 at 8 14 35 pm](https://cloud.githubusercontent.com/assets/13220018/20005139/65597106-a2cb-11e6-8a96-e5f74d642c95.png)

- The field also seems to accept manual numerical input

![screen shot 2016-11-04 at 8 14 46 pm](https://cloud.githubusercontent.com/assets/13220018/20005132/6041dc4e-a2cb-11e6-8cbd-4254a94008c0.png)

**Comment by raamdev** [comment]
@jaswsinc See above. ↑ Can we just show a message in place of the select box that says "This post has no comments." when there are no comments for the selected post?

**Comment by jaswsinc** [comment]
Yes, that sounds like a good idea to me also. Please fork that into a new issue.

**Comment by raamdev** [comment]
> Please fork that into a new issue.

Done. I don't think that issue warrants holding up the Comment Mail RC, so I'll leave that work for a future release milestone.

**Comment by renzms** [comment]
@raamdev 

Other than the issue here about the numerical values: https://github.com/websharks/comment-mail/issues/310

Tested to make sure it doesn't show unapproved comments and it's working! 👍

**Comment by raamdev** [comment]
**Comment Mail v161118** has been released and includes changes from this GitHub Issue. See the [v161118 announcement](http://comment-mail.com/comment-mail-v161118-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#299).
