### ISSUE TITLE
Feature Request: Add templates from Advanced Mode to Simple Mode to use shortcode

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail#305]
It would be nice if Comment Mail Pro included the templates from **Advanced Mode** in Simple mode. This way it offers a chance to edit the Advanced templates using shortcode for users who prefer that over coding in PHP or who may not be that well versed in PHP.

____

Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/14703

**Comment by tech55541** [comment]
+1 for this one. :)

**Comment by raamdev** [comment]
@renzms I'm not sure I understand what your suggesting. If the templates from Advanced Mode were included in Simple Mode, wouldn't that make the Simple Mode the same as Advanced Mode? I don't follow what you're suggesting... could you clarify for me?

**Comment by tech55541** [comment]
@raamdev, nope, not the same. Under Simple mode, you only have a certain number of templates you can edit, not really enough to change some common parts of the plugin. Under Advanced, of course you have all the templates.

My idea is to make more templates under Advanced to be available under Simple so you would not have to edit php and you could use Shortcodes. So in short, more templates under Simple that you can use Shortcodes with instead of php.

I would also be okay if more documentation was added on how to edit some of the php, but that would take a considerable amount of work whether if you just added more templates that could be edited with Shortcodes under Advanced.

Thanks.

**Comment by raamdev** [comment]
@tech55541 It's still not clear to me _which_ templates you're referring to. Can you give me an example of an Advanced template that you wish there was a Simple version of?

**Comment by tech55541** [comment]
@raamdev, templates such as Summary, Add/Edit Form,  Comment Form Subscr. Options. That template is available, but you can do very little when not in Advanced mode. The first 2 mentioned do not show up at all.

Thanks.

**Comment by raamdev** [comment]
@tech55541 Thank you. That clarifies it for me. So you're referring to **Comment Mail → Site Templates → Subscr. Summary Templates**. 

I just reviewed those templates and it looks like it will be quite challenging to make Simple template versions of those (which is probably why it wasn't done). Is there something specific in those templates that you want to modify? I'm trying to think of how we can simplify how they are presented in the Simple mode. What about the Summary and the Add/Edit Form are you wanting to customize?

**Comment by tech55541** [comment]
@raamdev, I just like making general changes to better suit my site. Also for accessibility reasons, things have had to be changed a little bit. Even simple wording changes is all I do at times, the Advanced templates are just to much for making simple changes here and there. It allows you access to very few templates under Simple and for beginners in php such as me, the plugin template sections need to be simplified.

Another option would be to expand your support policy to handle more coding related questions, then it wouldn't be to big of a deal.

Thanks.

**Comment by tech55541** [comment]
@raamdev, This is more specifically what I am trying to fix in the templates: #304 

Thanks.

**Comment by raamdev** [comment]
@tech55541 The reality is that some changes will not be possible without touching PHP, CSS, and/or JavaScript. The Simple templates are intended to allow quick, minor changes to the templates. Anything beyond a minor change would be easier to accomplish by editing PHP, which is why the Advanced Templates are provided. The Advanced Templates give you the ultimate flexibility but that does come with the cost of needing to understand some PHP. 

If we tried to make everything that can be customized in the Advanced Templates available in the Simple templates, we'd end up writing a custom programming language to make that possible. Instead of requiring that people learn a new custom programming language, it makes more sense to encourage learning a bit of PHP, since that knowledge will let you customize other things throughout WordPress (such as your theme). 

> This is more specifically what I am trying to fix in the templates: #304

I see. In that case, I'm going to close this GitHub issue in favor of that one, because I agree that accessibility is important and I'd rather get that fixed in the plugin than try to make those sorts of customizations available in the Simple templates.

**Comment by raamdev** [comment]
@tech55541 I should add that while our paid support does not cover questions about custom code, you're more than welcome to ask those questions in the [community forum](https://forums.wpsharks.com/c/comet-cache).

**Comment by tech55541** [comment]
@raamdev, Yes my above mentioned issue is much more important by far. I guess I see your point here. I also did not realize you had a forum, will be checking this out in the future.

Thanks.
