### ISSUE TITLE
Move Post Meta Box to a Lower Priority

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#57]
The Comment Mail Post Meta Box currently defaults to appearing _above_ the Publish meta box when editing or creating a new Post:

![2014-11-27_11-52-41](https://cloud.githubusercontent.com/assets/53005/5219933/04de0148-762c-11e4-9138-c5fab3243c56.png)

The Post Meta Box should be moved to a lower priority so that it doesn't appear above everything else, especially not above the Publish meta box, which should always appear at the top unless the user has specifically moved something above it.

**Comment by raamdev** [comment]
@jaswsinc Any update on this one? I'm triaging issues for the Next Release milestone, hoping to push out a RC early next week (January 25th). Just trying to figure out if this issue should be bumped to the Future Release milestone.

**Comment by jaswsinc** [comment]
The change I noted [here](https://github.com/websharks/comment-mail/issues/57#issuecomment-64949357) was merged in a while back. Looks like I never came back to update this issue though. I just confirmed that it is in there however. Referencing: https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/plugin.inc.php#L1031-L1032

---

> The Post Meta Box should be moved to a lower priority

The original reason for this issue being opened, I commented on [here](https://github.com/websharks/comment-mail/issues/57#issuecomment-64876583) and my view is still the same on that. I don't think it makes sense for a plugin to push anything that's new down to the bottom of a list that is customizable anyway. New = at the top = easier discovery.

---

So unless you still disagree and would like to change the priority, I think this can be closed now.

**Comment by raamdev** [comment]
@jaswsinc writes...
> I don't think it makes sense for a plugin to push anything that's new down to the bottom of a list that is customizable anyway. New = at the top = easier discovery.

Easier discovery, at the expense of making the Edit Post page more difficult to use...

The "Publish" meta box should always be at the top on the Edit Post page, at least until a site owner decides it shouldn't. If the site owner installed 3 plugins and each one followed the idea of "New = at the top = easier discovery", then eventually the "Publish" meta box could get hidden from view altogether and require the site owner (or one of its users; remember, not all sites have only one admin/editor/contributor) to hunt around and find one of the most basic, commonly used meta boxes on the Edit Post page.

This breaks one of the most common design principals: _Don't make me think._

In my mind it's about logical priority. What's the most logical priority on the Edit Post screen? Comment Mail and s2Member before the Publish box? (s2Member is different in this example because it's used to set permissions for a page; so it makes sense to put the s2Member meta box above Publish.) 

The Comment Mail meta box does nothing other than list recent subscriptions to that post... how is that more important than the Publish box, which contains the button to Update the post?! :smile: 

![2016-01-25_12-16-21](https://cloud.githubusercontent.com/assets/53005/12558537/0818b5a8-c35e-11e5-90ec-d918be2ee220.png)

**Comment by jaswsinc** [comment]
> In my mind it's about logical priority. What's the most logical priority on the Edit Post screen?

I'm not disagreeing with you on this. However, there simply is no way to know what is the right priority for any given site, or for any given site owner's interpretation of what works best for them. That's why these widgets support drag n' drop. So you can order them to your liking.

Putting anything that's new down at the bottom is unfriendly in my view. It makes discovery more difficult. We are not WordPress, we are Comment Mail. Comment Mail's objective is to make your experience with our plugin easy, enjoyable, and impressive. If you completely miss the metabox because it is down at the bottom where you never look, we could be missing an opportunity there.

Your call though. Either way works for me. A site owner can rearrange them on their own. I just don't see this change as being an improvement. If anything, it seems like it pulls attention away from a new plugin that you just installed, and insteads puts focus on WordPress core. I don't care about WP core in this context.

**Comment by raamdev** [comment]
> Putting anything that's new down at the bottom is unfriendly in my view. It makes discovery more difficult. We are not WordPress, we are Comment Mail. Comment Mail's objective is to make your experience with our plugin easy, enjoyable, and impressive.

Right, but I'm not advocating that we put it at the bottom. I'm simply saying it shouldn't be at the very very top, with a `high` priority. It's not a high-priority box. It doesn't contain any high-priority information (at least in the majority of all cases where that information will be used). 

It's an informational box that lists the Comment Mail subscriptions associated with that post. (You can click the email addresses to visit the subscriptions list, yes, but again, not a 'common task' in the majority of all cases where someone edits a post.)

For that matter, the `side` context feels wrong in this case, as the `side` context seems mostly useful for smaller, input-style bits of information. For something like a list of recent subscriptions (with email addresses that might be longer than the width of the small Meta Box), a `normal` context feels more appropriate:

![2016-01-26_06-55-17](https://cloud.githubusercontent.com/assets/53005/12580060/8793a738-c3fa-11e5-813c-27f4f67122a6.png)

**Comment by jaswsinc** [comment]
> Right, but I'm not advocating that we put it at the bottom. I'm simply saying it shouldn't be at the very very top, with a high priority. It's not a high-priority box. It doesn't contain any high-priority information (at least in the majority of all cases where that information will be used).

I see. Well, that seems better. Not putting it all the way down at the bottom. I really don't have a problem with it being moved anywhere else either for matter, even though my last response probably came off that way. Sorry. I was just trying to share my point of view. I don't see this as being broken, but I don't have a problem with it being moved around if that's what you prefer.

> For that matter, the side context feels wrong in this case..

Hmm. I don't have an opinion on that myself; i.e., I'm not sure one way or the other. My general feeling is that this information can be vital to some people under various conditions, and not even worth looking at in others. Which makes me glad that these are all draggable.

In many respects, this box is sort of a scoreboard for how successful a post is, and if a team is using the number of comments/subscriptions as a way of gauging the success of a post, it is important for them to see. For instance, a Contributor might have very little access to a site, and perhaps this box is something they look at very often, because it is one of their only ways of gauging how successful their content is becoming/became. That seems somewhat common to me.

On the other hand, I'm guessing that a more common scenario is that people will see this, use it for what it's worth, but learn to ignore it over time. So I'm not disagreeing with your feeling about the priority of this box. However, my view about easy discovery is still the same. I still think that making it easy to discover should be a top priority. Otherwise it can potentially go unnoticed. Right now, that's not a huge deal, but as this is enhanced in the future this box may contain more useful information and we won't want people to miss it. People miss things so easily. If it's not right in their face, it just blends in with everything else.

**Comment by raamdev** [comment]
@jaswsinc Thank you for going back and forth with me on this. :smile: I've made the call. ↑

**Comment by jaswsinc** [comment]
Cool! :-) I will learn to accept this later in life. :laughing:

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Moved the default location for the Subscriptions Meta Box on the Post Edit screen so that it shows up underneath the post editing area instead of above the Publish box. See [Issue #57](https://github.com/websharks/comment-mail/issues/57#issuecomment-174482908).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Moved the default location for the Subscriptions Meta Box on the Post Edit screen so that it shows up underneath the post editing area instead of above the Publish box. See [Issue #57](https://github.com/websharks/comment-mail/issues/57#issuecomment-174482908).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#57).
